# Generated by Django 5.0.1 on 2024-02-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0008_cartorderitem_tag_remove_product_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='discounted_price',
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(null=True),
        ),
    ]
