# Generated by Django 5.0.1 on 2024-02-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0010_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
