# Generated by Django 5.0.1 on 2024-02-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0019_product_short_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartOrderItem',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_status',
        ),
    ]
